esphome:
  min_version: 2023.6.0
  name: espsharan
  friendly_name: espSharan
  includes:
   - webasto.h

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.156
    gateway: 192.168.1.254
    subnet: 255.255.255.0   

api:
  encryption:
    key: "BD7oYgph6lN0iAXuwh22MzvJORVGe+ZGwhR2K6ElwIQ="

ota:
  - platform: esphome
    password: "f6a56179190bf80773a1397cfaff6731"

uart:
  id: uart_bus
  tx_pin: 22
  rx_pin: 21
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1

custom_component:
- lambda: |-
    auto my_custom = new Webasto(id(uart_bus));
    return {my_custom};
  components:
    - id: my_custom_id
    
interval:
  - interval: 10s
    then:
      - if:
          condition:
            - lambda: "return id(remain).state > 0;"
          then:
            - number.decrement:
                id: remain
                cycle: false
      - if:
          condition:
            - lambda: "return id(remain).state < 0;"
          then:
            - number.set:
                id: remain
                value: 0
            - switch.turn_off: sw_heat
            - switch.turn_off: sw_vent

button:
  - platform: restart
    name: "Restart"

switch:
  - platform: template
    id: sw_vent
    optimistic: true
    on_turn_on:
      - switch.turn_off: sw_heat
      - lambda: "static_cast<Webasto*>(id(my_custom_id))->VentOn();"
      - number.set:
          id: remain
          value: !lambda "return id(runtime).state;"
    on_turn_off:
      - lambda: "static_cast<Webasto*>(id(my_custom_id))->Off();"
      - number.set:
          id: remain
          value: 0

  - platform: template
    name: "Heizen"
    optimistic: true
    id: sw_heat
    on_turn_on:
      - switch.turn_off: sw_vent
      - lambda: "static_cast<Webasto*>(id(my_custom_id))->HeatOn();"
      - number.set:
          id: remain
          value: !lambda "return id(runtime).state;"
    on_turn_off:
      - lambda: "static_cast<Webasto*>(id(my_custom_id))->Off();"
      - number.set:
          id: remain
          value: 0

  - platform: gpio
    #name: "LIN Modul"
    pin: GPIO23
    id: gpio23_switch
    restore_mode: RESTORE_DEFAULT_ON

number:
  - platform: template
    #name: "Verbleibend"
    icon: mdi:timer-sand
    id: remain
    initial_value: 0
    step: 0.1
    min_value: -0.5
    max_value: 1440
    unit_of_measurement: 'min'
    mode: box
    optimistic: true

  - platform: template
    name: "Laufzeit"
    icon: mdi:timer
    id: runtime
    restore_value: false
    initial_value: 30
    step: 5
    min_value: 0
    max_value: 60
    unit_of_measurement: 'min'
    mode: box
    optimistic: true

sensor:
  - platform: template
    name: "Verbleibend"
    id: remain_sensor
    icon: mdi:timer-sand
    unit_of_measurement: "min"
    update_interval: 1s
    lambda: |-
      return id(remain).state;

  - platform: wifi_signal
    name: "WLAN Signalstärke"
    icon: mdi:wifi



  - platform: template
    name: "Betriebsstunden (Heizung aktiv)"
    icon: mdi:timer-outline
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_06.working_hours;"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 30s

  - platform: template
    name: "Gesamtbetriebsstunden"
    icon: mdi:timer
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_06.operating_hours;"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 30s

  - platform: template
    name: "Startzähler"
    icon: mdi:counter
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_06.start_counter;"
    unit_of_measurement: "-"
    accuracy_decimals: 0
    update_interval: 30s

  - platform: template
    name: "Wassertemperatur"
    icon: mdi:thermometer-water
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_05.temperature;"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    update_interval: 5s

  - platform: template
    name: "Batteriespannung"
    icon: mdi:car-battery
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_05.voltage;"
    unit_of_measurement: "V"
    accuracy_decimals: 1
    update_interval: 5s
    
binary_sensor:
  - platform: template
    name: "Verbrennungslüfter"
    icon: mdi:fan
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_03.combustion_fan;"

  - platform: template
    name: "Glühkerze"
    icon: mdi:fire
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_03.glowplug;"

  - platform: template
    name: "Kraftstoffpumpe"
    icon: mdi:fuel
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_03.fuel_pump;"

  - platform: template
    name: "Zirkulationspumpe"
    icon: mdi:pump
    lambda: "return static_cast<Webasto*>(id(my_custom_id))->state_50_03.circulation_pump;"


  
